import { useState, useEffect } from 'react'
import api from '../../../services/api'

export function EchantillonsPage() {
  const [echantillons, setEchantillons] = useState<any[]>([])
  const [typesEchantillon, setTypesEchantillon] = useState<any[]>([])
  const [demandes, setDemandes] = useState<any[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [showModal, setShowModal] = useState(false)
  const [searchTerm, setSearchTerm] = useState('')
  const [filterStatut, setFilterStatut] = useState('TOUS')
  const [editingEchantillon, setEditingEchantillon] = useState<any>(null)
  const [demandeSearch, setDemandeSearch] = useState('')
  const [showDemandeDropdown, setShowDemandeDropdown] = useState(false)
  const [formData, setFormData] = useState({
    code_echantillon: '',
    designation: '',
    type_echantillon: '',
    statut: 'RECEPTIONNE',
    emplacement_stockage: '',
    date_reception: new Date().toISOString().split('T')[0],
    demande: '',
    quantite: '',
    description: ''
  })

  useEffect(() => {
    loadEchantillons()
    loadTypesEchantillon()
    loadDemandes()
  }, [])

  const loadEchantillons = async () => {
    try {
      setIsLoading(true)
      const data = await api.echantillons.list()
      setEchantillons(data.results || data || [])
    } catch (error) {
      console.error('Erreur chargement échantillons:', error)
    } finally {
      setIsLoading(false)
    }
  }

  const loadTypesEchantillon = async () => {
    try {
      const response = await fetch(`${import.meta.env.VITE_API_URL || 'http://localhost:8000/api'}/demandes/types-analyse/`, {
        headers: {
          'Authorization': `Bearer ${localStorage.getItem('lanema_token')}`
        }
      })
      if (response.ok) {
        const data = await response.json()
        setTypesEchantillon(Array.isArray(data) ? data : (data.results || data || []))
      }
    } catch (error) {
      console.error('Erreur chargement types:', error)
    }
  }

  const loadDemandes = async () => {
    try {
      const response = await fetch(`${import.meta.env.VITE_API_URL || 'http://localhost:8000/api'}/demandes/demandes-simple/`, {
        headers: {
          'Authorization': `Bearer ${localStorage.getItem('lanema_token')}`
        }
      })
      if (response.ok) {
        const data = await response.json()
        setDemandes(Array.isArray(data) ? data : (data.results || data || []))
      }
    } catch (error) {
      console.error('Erreur chargement demandes:', error)
    }
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    try {
      if (editingEchantillon) {
        await api.echantillons.update(editingEchantillon.id, formData)
      } else {
        // Remove code_echantillon for new samples (auto-generated by backend)
        const { code_echantillon, ...dataToSend } = formData
        await api.echantillons.create(dataToSend)
      }
      setShowModal(false)
      setEditingEchantillon(null)
      resetForm()
      loadEchantillons()
    } catch (error) {
      console.error('Erreur sauvegarde:', error)
    }
  }

  const handleEdit = (echantillon: any) => {
    setEditingEchantillon(echantillon)
    setFormData({
      code_echantillon: echantillon.code_echantillon || '',
      designation: echantillon.designation || '',
      type_echantillon: echantillon.type_echantillon?.nom || echantillon.type_echantillon || '',
      statut: echantillon.statut || 'RECEPTIONNE',
      emplacement_stockage: echantillon.emplacement_stockage || '',
      date_reception: echantillon.date_reception || new Date().toISOString().split('T')[0],
      demande: echantillon.demande || '',
      quantite: echantillon.quantite || '',
      description: echantillon.description || ''
    })
    // Set demande search text for edit mode
    const demandeLabel =
      echantillon.demande_numero ||
      (typeof echantillon.demande === 'object'
        ? (echantillon.demande.label || `${echantillon.demande.numero} - ${echantillon.demande.type_analyse}`)
        : '')
    setDemandeSearch(demandeLabel || '')
    setShowModal(true)
  }

  const resetForm = () => {
    setFormData({
      code_echantillon: '',
      designation: '',
      type_echantillon: '',
      statut: 'RECEPTIONNE',
      emplacement_stockage: '',
      date_reception: new Date().toISOString().split('T')[0],
      demande: '',
      quantite: '',
      description: ''
    })
    setDemandeSearch('')
    setShowDemandeDropdown(false)
  }

  const statutBadgeColor = (statut: string) => {
    const colors: Record<string, string> = {
      'RECEPTIONNE': 'bg-slate-100 text-slate-700',
      'EN_ATTENTE': 'bg-amber-50 text-amber-700',
      'EN_ANALYSE': 'bg-lanema-blue-50 text-lanema-blue-700',
      'TERMINE': 'bg-emerald-50 text-emerald-700',
      'ARCHIVE': 'bg-slate-100 text-slate-500'
    }
    return colors[statut] || 'bg-slate-100 text-slate-600'
  }

  const filteredEchantillons = echantillons.filter(e => {
    const matchesSearch = 
      e.code_echantillon?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      e.designation?.toLowerCase().includes(searchTerm.toLowerCase())
    const matchesStatut = filterStatut === 'TOUS' || e.statut === filterStatut
    return matchesSearch && matchesStatut
  })

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold text-slate-900">Gestion des échantillons</h1>
          <p className="text-sm text-slate-600 mt-1">Enregistrez et suivez tous les échantillons du laboratoire</p>
        </div>
        <button 
          onClick={() => {
            setEditingEchantillon(null)
            resetForm()
            setShowModal(true)
          }}
          className="inline-flex items-center gap-2 px-4 py-2.5 text-sm font-semibold text-white bg-lanema-blue-600 hover:bg-lanema-blue-700 rounded-lg shadow-md transition"
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
          </svg>
          Nouvel échantillon
        </button>
      </div>

      {/* Stats */}
      {isLoading ? (
        <div className="grid grid-cols-1 md:grid-cols-5 gap-4">
          {[...Array(5)].map((_, i) => (
            <div key={i} className="lanema-card p-4 animate-pulse">
              <div className="h-4 w-24 bg-slate-200 rounded mb-2"></div>
              <div className="h-8 w-16 bg-slate-200 rounded"></div>
            </div>
          ))}
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-5 gap-4">
          <div className="lanema-card p-4">
            <div className="text-xs text-slate-500 mb-1">Total</div>
            <div className="text-2xl font-semibold text-slate-900">{echantillons.length}</div>
          </div>
          <div className="lanema-card p-4">
            <div className="text-xs text-slate-500 mb-1">Réceptionnés</div>
            <div className="text-2xl font-semibold text-slate-600">
              {echantillons.filter(e => e.statut === 'RECEPTIONNE').length}
            </div>
          </div>
          <div className="lanema-card p-4">
            <div className="text-xs text-slate-500 mb-1">En analyse</div>
            <div className="text-2xl font-semibold text-lanema-blue-600">
              {echantillons.filter(e => e.statut === 'EN_ANALYSE').length}
            </div>
          </div>
          <div className="lanema-card p-4">
            <div className="text-xs text-slate-500 mb-1">Terminés</div>
            <div className="text-2xl font-semibold text-emerald-600">
              {echantillons.filter(e => e.statut === 'TERMINE').length}
            </div>
          </div>
          <div className="lanema-card p-4">
            <div className="text-xs text-slate-500 mb-1">Archivés</div>
            <div className="text-2xl font-semibold text-slate-500">
              {echantillons.filter(e => e.statut === 'ARCHIVE').length}
            </div>
          </div>
        </div>
      )}

      {/* Filters */}
      <div className="lanema-card p-4">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <input
            type="text"
            placeholder="Rechercher par code ou désignation..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="px-4 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-lanema-blue-500"
          />
          <select
            value={filterStatut}
            onChange={(e) => setFilterStatut(e.target.value)}
            className="px-4 py-2 text-sm border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-lanema-blue-500"
          >
            <option value="TOUS">Tous les statuts</option>
            <option value="RECEPTIONNE">Réceptionnés</option>
            <option value="EN_ATTENTE">En attente</option>
            <option value="EN_ANALYSE">En analyse</option>
            <option value="TERMINE">Terminés</option>
            <option value="ARCHIVE">Archivés</option>
          </select>
        </div>
      </div>

      {/* Table */}
      {isLoading ? (
        <div className="lanema-card p-6 animate-pulse">
          <div className="space-y-3">
            {[...Array(5)].map((_, i) => (
              <div key={i} className="h-16 bg-slate-200 rounded"></div>
            ))}
          </div>
        </div>
      ) : filteredEchantillons.length === 0 ? (
        <div className="lanema-card p-12 text-center">
          <div className="w-16 h-16 rounded-full bg-slate-100 flex items-center justify-center mx-auto mb-4">
            <svg className="w-8 h-8 text-slate-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
            </svg>
          </div>
          <h3 className="text-lg font-semibold text-slate-900 mb-1">Aucun échantillon trouvé</h3>
          <p className="text-sm text-slate-600">Commencez par enregistrer un nouvel échantillon</p>
        </div>
      ) : (
        <div className="lanema-card overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-slate-50">
                <tr>
                  <th className="px-4 py-3 text-left text-xs font-medium text-slate-600">Code</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-slate-600">Désignation</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-slate-600">Type</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-slate-600">Date réception</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-slate-600">Localisation</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-slate-600">Statut</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-slate-600">Actions</th>
                </tr>
              </thead>
              <tbody>
                {filteredEchantillons.map((echantillon) => (
                  <tr key={echantillon.id} className="border-t border-slate-100 hover:bg-slate-50 transition">
                    <td className="px-4 py-3 text-sm font-medium text-slate-900">
                      {echantillon.code_echantillon}
                    </td>
                    <td className="px-4 py-3 text-sm text-slate-700 max-w-xs truncate">
                      {echantillon.designation}
                    </td>
                    <td className="px-4 py-3 text-sm text-slate-600">
                      {echantillon.type_echantillon?.nom || echantillon.type_echantillon || 'N/A'}
                    </td>
                    <td className="px-4 py-3 text-sm text-slate-600">
                      {echantillon.date_reception ? new Date(echantillon.date_reception).toLocaleDateString('fr-FR') : 'N/A'}
                    </td>
                    <td className="px-4 py-3 text-sm text-slate-600">
                      {echantillon.emplacement_stockage || 'Non définie'}
                    </td>
                    <td className="px-4 py-3 text-sm">
                      <span className={`inline-flex items-center px-2 py-0.5 text-xs font-medium rounded-full ${statutBadgeColor(echantillon.statut)}`}>
                        {echantillon.statut?.replace('_', ' ')}
                      </span>
                    </td>
                    <td className="px-4 py-3">
                      <div className="flex items-center gap-2">
                        <button 
                          onClick={() => handleEdit(echantillon)}
                          className="text-sm text-lanema-blue-600 hover:text-lanema-blue-700 font-medium hover:underline"
                        >
                          Éditer
                        </button>
                        {echantillon.qr_code_url && (
                          <a
                            href={echantillon.qr_code_url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-sm text-slate-600 hover:text-slate-700"
                            title="Voir QR Code"
                          >
                            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v1m6 11h2m-6 0h-2v4m0-11v3m0 0h.01M12 12h4.01M16 20h4M4 12h4m12 0h.01M5 8h2a1 1 0 001-1V5a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1zm12 0h2a1 1 0 001-1V5a1 1 0 00-1-1h-2a1 1 0 00-1 1v2a1 1 0 001 1zM5 20h2a1 1 0 001-1v-2a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1z" />
                            </svg>
                          </a>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Modal */}
      {showModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg w-full max-w-2xl max-h-[90vh] overflow-y-auto">
            <div className="p-6">
              <div className="flex items-center justify-between mb-6">
                <h3 className="text-lg font-semibold text-slate-900">
                  {editingEchantillon ? 'Modifier l\'échantillon' : 'Nouvel échantillon'}
                </h3>
                <button 
                  onClick={() => {
                    setShowModal(false)
                    setEditingEchantillon(null)
                  }}
                  className="text-slate-400 hover:text-slate-600"
                >
                  <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>

              <form onSubmit={handleSubmit} className="space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">
                      Code échantillon (auto-généré)
                    </label>
                    <input
                      type="text"
                      value={formData.code_echantillon}
                      onChange={(e) => setFormData({...formData, code_echantillon: e.target.value})}
                      className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-lanema-blue-500 bg-slate-50"
                      placeholder="Généré automatiquement"
                      disabled={!editingEchantillon}
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">
                      Type d'échantillon *
                    </label>
                    <select
                      value={formData.type_echantillon}
                      onChange={(e) => setFormData({...formData, type_echantillon: e.target.value})}
                      className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-lanema-blue-500"
                      required
                    >
                      <option value="">Sélectionner un type</option>
                      {typesEchantillon.map(type => (
                        <option key={type.id} value={type.nom}>
                          {type.nom}
                        </option>
                      ))}
                    </select>
                  </div>

                  <div className="md:col-span-2">
                    <label className="block text-sm font-medium text-slate-700 mb-1">
                      Désignation *
                    </label>
                    <input
                      type="text"
                      value={formData.designation}
                      onChange={(e) => setFormData({...formData, designation: e.target.value})}
                      className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-lanema-blue-500"
                      placeholder="Description de l'échantillon"
                      required
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">
                      Quantité
                    </label>
                    <input
                      type="text"
                      value={formData.quantite}
                      onChange={(e) => setFormData({...formData, quantite: e.target.value})}
                      className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-lanema-blue-500"
                      placeholder="25 kg, 10 pièces..."
                    />
                  </div>

                  <div className="relative">
                    <label className="block text-sm font-medium text-slate-700 mb-1">
                      Demande d'analyse *
                    </label>
                    <input
                      type="text"
                      value={demandeSearch}
                      onChange={(e) => {
                        setDemandeSearch(e.target.value)
                        setShowDemandeDropdown(true)
                      }}
                      onFocus={() => setShowDemandeDropdown(true)}
                      className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-lanema-blue-500"
                      placeholder="Rechercher une demande..."
                    />
                    {showDemandeDropdown && (
                      <div className="absolute z-50 w-full mt-1 bg-white border border-slate-300 rounded-lg shadow-lg max-h-48 overflow-y-auto">
                        {demandes
                          .filter(d => {
                            const label = d.label || `${d.numero} - ${d.type_analyse}`
                            return label.toLowerCase().includes(demandeSearch.toLowerCase())
                          })
                          .map(demande => (
                            <div
                              key={demande.id}
                              onClick={() => {
                                setFormData({...formData, demande: demande.id})
                                setDemandeSearch(demande.label || `${demande.numero} - ${demande.type_analyse}`)
                                setShowDemandeDropdown(false)
                              }}
                              className={`px-4 py-2 cursor-pointer hover:bg-lanema-blue-50 text-sm ${
                                formData.demande === demande.id ? 'bg-lanema-blue-100 text-lanema-blue-700' : 'text-slate-700'
                              }`}
                            >
                              {demande.label || `${demande.numero} - ${demande.type_analyse}`}
                            </div>
                          ))
                        }
                        {demandes.filter(d => {
                          const label = d.label || `${d.numero} - ${d.type_analyse}`
                          return label.toLowerCase().includes(demandeSearch.toLowerCase())
                        }).length === 0 && (
                          <div className="px-4 py-2 text-sm text-slate-500">Aucune demande trouvée</div>
                        )}
                      </div>
                    )}
                    <input type="hidden" value={formData.demande} required />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">
                      Date de réception *
                    </label>
                    <input
                      type="date"
                      value={formData.date_reception}
                      onChange={(e) => setFormData({...formData, date_reception: e.target.value})}
                      className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-lanema-blue-500"
                      required
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">
                      Statut *
                    </label>
                    <select
                      value={formData.statut}
                      onChange={(e) => setFormData({...formData, statut: e.target.value})}
                      className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-lanema-blue-500"
                    >
                      <option value="RECEPTIONNE">Réceptionné</option>
                      <option value="EN_ATTENTE">En attente</option>
                      <option value="EN_ANALYSE">En analyse</option>
                      <option value="TERMINE">Terminé</option>
                      <option value="ARCHIVE">Archivé</option>
                    </select>
                  </div>

                  <div className="md:col-span-2">
                    <label className="block text-sm font-medium text-slate-700 mb-1">
                      Emplacement de stockage
                    </label>
                    <input
                      type="text"
                      value={formData.emplacement_stockage}
                      onChange={(e) => setFormData({...formData, emplacement_stockage: e.target.value})}
                      className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-lanema-blue-500"
                      placeholder="Salle A - Étagère 3, Zone B..."
                    />
                  </div>

                  <div className="md:col-span-2">
                    <label className="block text-sm font-medium text-slate-700 mb-1">
                      Description
                    </label>
                    <textarea
                      value={formData.description}
                      onChange={(e) => setFormData({...formData, description: e.target.value})}
                      className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-lanema-blue-500"
                      placeholder="Description détaillée de l'échantillon"
                      rows={3}
                    />
                  </div>
                </div>

                <div className="flex gap-3 pt-4">
                  <button 
                    type="submit" 
                    className="flex-1 px-4 py-2.5 text-sm font-semibold text-white bg-lanema-blue-600 hover:bg-lanema-blue-700 rounded-lg transition"
                  >
                    {editingEchantillon ? 'Mettre à jour' : 'Créer l\'échantillon'}
                  </button>
                  <button 
                    type="button"
                    onClick={() => {
                      setShowModal(false)
                      setEditingEchantillon(null)
                    }}
                    className="flex-1 px-4 py-2.5 text-sm font-semibold text-slate-700 bg-slate-100 hover:bg-slate-200 rounded-lg transition"
                  >
                    Annuler
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
